# Generated by Django 3.0.4 on 2020-03-31 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcategory',
            name='organizations',
            field=models.ManyToManyField(blank=True, related_name='subcategories', to='core.Organization'),
        ),
    ]
